nl_syntax	:== nl_rule nl_syntax2 | nl_rule
nl_syntax2	:== nl_syntax2 nl_newlines nl_rule | nl_blaat nl_newlines l_expr_sep nl_list
nl_rule		:== l_rule_name l_assignment nl_expr
nl_expr		:== nl_list | nl_expr l_expr_sep nl_list
nl_list		:== nl_symbol | nl_list nl_symbol
nl_symbol	:== l_rule_name | l_rule_name l_optional | l_rule_name l_kleene | l_rule_name l_plus
nl_newlines :== l_newline | nl_newlines l_newline
