nl_syntax	:== nl_rule 
nl_syntax	:== nl_syntax nl_newlines nl_rule
nl_syntax	:== nl_syntax nl_newlines nl_alt_rule
nl_rule		:== l_rule_name l_assignment nl_expr
nl_alt_rule	:== l_expr_sep nl_list
nl_expr		:== nl_symbol
nl_expr		:== nl_expr nl_symbol
nl_symbol	:== l_rule_name
nl_symbol	:== l_rule_name l_optional
nl_symbol	:== l_rule_name l_kleene
nl_symbol	:== l_rule_name l_plus
nl_newlines :== l_newline
nl_newlines	:== nl_newlines l_newline
